# used by reinforcement operatives
- type: startingGear
  id: SyndicateOperativeGearNoUplink
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: PlushieCarp # instead of uplink

- type: startingGear
  id: SyndicateOperativeReinforcementGear
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio50TC