- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 14400 # 4 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 14400 # 4 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  - External # goobstation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  # Shitmed Change
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      SpeedModifier: 2.5

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetAltMedical # Goobstation
    belt: ClothingBeltMilitaryWebbingCMOFilled # Goobstation
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation
