- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 14400 # 4 hrs
    - !type:OverallPlaytimeRequirement
      time: 14400 # 4 hrs
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - External # goobstation
  extendedAccess:
  - Chemistry
  - Research # ShibaStation - Added Research to Paramedic access
  special:
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      SpeedModifier: 1.75

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
  storage:
    back:
    - EmergencyRollerBedSpawnFolded
