# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

Project-Condor:
  org: space-wizards
  project: 2
  inbox: Inbox
  labels:
    "W: In Progress": "In Progress"
    "W: Discussion": "Design and Discussion"
    "W: Backlog": "Backlog"
    "W: Next": "Next"
