- type: startingGear
  id: HelldiverGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    back: WeaponRifleM90
    belt: ClothingBeltMercWebbingHelldiverFilled
    mask: ClothingMaskGasMerc
    eyes: ClothingEyesGlassesMercenary # Night Vision when added
    ears: ClothingHeadsetAltFreelancer
    gloves: ClothingHandsMercGlovesCombat
    neck: ClothingNeckCloakHelldiver
    head: ClothingHeadHelmetHelldiver
    outerClothing: ClothingOuterArmorHelldiver
    suitstorage: DoubleEmergencyOxygenTankFilled
    shoes: ClothingShoesBootsMercFilled
    id: HelldiverPDA
    pocket1: ToolDebug
    pocket2: WeaponPistolEchis

- type: entity
  parent: ClothingBeltMercWebbing
  id: ClothingBeltMercWebbingHelldiverFilled
  suffix: Helldiver, Filled
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:NestedSelector
        tableId: HelldiverBeltFillTable

- type: entityTable
  id: HelldiverBeltFillTable
  table: !type:AllSelector
    children:
    - id: MagazineRifle
      amount: !type:ConstantNumberSelector
        value: 3
    - id: MagazineBoxRifleBig
    - id: ExGrenade
      amount: !type:ConstantNumberSelector
        value: 2
    - id: MedkitCombatFilled
