- type: job
  id: RadioHost
  name: job-name-radiohost
  description: job-description-radiohost
  playTimeTracker: JobRadioHost
  startingGear: RadioHostGear
  icon: "JobIconRadioHost"
  supervisors: job-supervisors-hop
  access:
  - Maintenance
  - RadioStation

- type: startingGear
  id: RadioHostGear
  equipment:
    ears: ClothingHeadsetAltRadioHost
    eyes: ClothingEyesGlassesSunglasses
    jumpsuit: ClothingUniformJumpsuitReporter
    shoes: ClothingShoesColorBlack
    back: ClothingBackpackSatchel
    id: RadioHostPDA

- type: chameleonOutfit
  id: RadioHostChameleonOutfit
  job: RadioHost
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    ear: ClothingHeadsetAltRadioHost
    jumpsuit: ClothingUniformJumpsuitReporter
    shoes: ClothingShoesColorBlack
    id: RadioHostPDA

