- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 14400 #4 hrs
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  guides: [ Robotics ]
  goobcoins: 20
  access:
  - Research
  - Maintenance
  - Robotics

- type: startingGear
  id: RoboticistGear
  equipment:
    ears: ClothingHeadsetRobotics
    eyes: ClothingEyesHudDiagnostic

- type: chameleonOutfit
  id: RoboticistChameleonOutfit
  job: Roboticist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRobo
    gloves: ClothingHandsGlovesRobohands
    ear: ClothingHeadsetRobotics
    jumpsuit: ClothingUniformJumpsuitRoboticist
    shoes: ClothingShoesColorBlack
    id: RoboticistPDA
