# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

- type: stack
  parent: BaseMediumStack
  id: CableDet
  name: stack-explosive-cord
  icon: { sprite: "/Textures/Objects/Tools/cable-coils.rsi", state: coilex-30 }
  spawn: CableDetStack1
