- type: job
  id: NanotrasenCareerTrainer
  name: job-name-nct
  description: job-description-nct
  playTimeTracker: JobNanotrasenCareerTrainer
  goobcoins: 45
  weight: 20
  startingGear: NanotrasenCareerTrainerGear
  icon: "JobIconNanotrasenTrainer"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  whitelisted: true # 1984
  setPreference: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant, KravMagaImplant ] # Krav for self-defense, don't want to be defenceless chud, dont want to be too OP.
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Condemned
        soulOwnedNotDevil: true

- type: startingGear
  id: NanotrasenCareerTrainerGear
  equipment:
    id: TrainerPDA
    ears: ClothingHeadsetAltCentCom
    eyes: ClothingEyesGlassesCentCommNoThermal
    pocket1: Flash
    pocket2: FoodSnackLollypopWrappedCentComm # Come on, it's a trademark at this point.
    back: ClothingModsuitTrainerFilled

- type: chameleonOutfit
  id: NanotrasenCareerTrainerChameleonOutfit
  job: NanotrasenCareerTrainer
  equipment:
    eyes: ClothingEyesGlassesCentComm
    mask: ClothingMaskBreath
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesHeavyGoldenTrim
    jumpsuit: ClothingUniformJumpsuitTrainer
    id: TrainerPDA
    back: ClothingModsuitTrainer
    shoes: ClothingShoesBootsLaceup
    outerClothing: ClothingOuterWinterCoatTrainer
    head: ClothingHeadHatTrainer
    neck: ClothingNeckChameleon
