- type: job
  id: NanotrasenCareerTrainer
  name: job-name-nct
  description: job-description-nct
  playTimeTracker: JobNanotrasenCareerTrainer
  requirements: # Omu, add requirements
    - !type:RoleTimeRequirement
      role: JobNanotrasenCareerTrainer
      time: 360000 #100 hrs - Omu
  goobcoins: 45
  weight: 20
  startingGear: NanotrasenCareerTrainerGear
  icon: "JobIconNanotrasenTrainer"
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  canBeAntag: false
  whitelisted: true # 1984
  setPreference: true # Omu, enable NCT for admins
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant ]
#  - !type:AddComponentSpecial # Intentionally not command. I don't want them to ruin rev rounds.
#    components:
#    - type: CommandStaff

- type: startingGear
  id: NanotrasenCareerTrainerGear
  equipment:
    id: TrainerPDA
    ears: ClothingHeadsetAltCentCom
    eyes: ClothingEyesGlassesCentComm
    pocket1: WeaponDisabler
    pocket2: FoodSnackLollypopWrappedCentComm # Come on, it's a trademark at this point.
  storage:
    back:
    - Flash
    - TelescopicBatonAdvanced
    - CentralCommandBusinessCard

- type: chameleonOutfit
  id: NanotrasenCareerTrainerChameleonOutfit
  job: NanotrasenCareerTrainer
  equipment:
    eyes: ClothingEyesGlassesCentComm
    mask: ClothingMaskBreath
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesHeavyGoldenTrim
    jumpsuit: ClothingUniformJumpsuitTrainer
    id: TrainerPDA
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsLaceup
    outerClothing: ClothingOuterWinterCoatTrainer
    head: ClothingHeadHatTrainer
    neck: ClothingNeckChameleon
