[net]
tickrate = 30

[netres]
limit = 25.0

[infolinks]
discord = "https://discord.ss14.ru"
github = "https://github.com/space-syndicate/Goob-Station"
wiki = "https://station14.ru"
patreon = "https://boosty.to/corvax"
appeal = "https://discord.ss14.ru"
bug_report = "https://discord.ss14.ru"
website = "https://ss14.ru"

[viewport]
maximum_width = 26

[game]
lobbyduration = 240
map_pool = "CorvaxMapPool"
round_restart_time = 240
fallbackpreset = "secret"
defaultpreset = "secret"

[events]
enabled = true

[server]
rules_file = "CorvaxRuleset"

[discord]
rich_main_icon_id = "corvax"

[admin]
see_own_notes = true
admins_count_in_playercount = true

[contraband]
icons_enabled = true
