[game]
hostname = "ğŸ›°ï¸ CorvaxGoob â€” ğŸŒ• Ğ›ÑĞ¼ĞµĞ½ ğŸª [MRP+] [TTS]"
desc = "Corvax â€” Ğ¿ĞµÑ€Ğ²Ñ‹Ğ¹ Ñ€ÑƒÑÑĞºĞ¾ÑĞ·Ñ‹Ñ‡Ğ½Ñ‹Ğ¹ Ğ¿Ñ€Ğ¾ĞµĞºÑ‚ Ğ² Space Station 14!\nâ€¢ ğŸ› ï¸ ĞĞ° ÑÑ‚Ğ¾Ğ¼ ÑĞµÑ€Ğ²ĞµÑ€Ğµ Ğ¸ÑĞ¿Ğ¾Ğ»ÑŒĞ·ÑƒĞµÑ‚ÑÑ Ğ¸Ğ·Ğ¼ĞµĞ½ĞµĞ½Ğ½Ğ°Ñ ÑĞ±Ğ¾Ñ€ĞºĞ° Goob Station.\n   Ğ‘Ğ¾Ğ»ÑŒÑˆĞµ ĞºĞ¾Ğ½Ñ‚ĞµĞ½Ñ‚Ğ°, Ğ²Ğ¾Ğ·Ğ¼Ğ¾Ğ¶Ğ½Ğ¾ÑÑ‚ĞµĞ¹ Ğ¸ Ğ²Ğ·Ğ°Ğ¸Ğ¼Ğ¾Ğ´ĞµĞ¹ÑÑ‚Ğ²Ğ¸Ñ!\nâ€¢ ğŸ”´ ĞŸĞ¾Ğ²Ñ‹ÑˆĞµĞ½Ğ½Ñ‹Ğµ Ñ‚Ñ€ĞµĞ±Ğ¾Ğ²Ğ°Ğ½Ğ¸Ñ Ğº RP.\nâ€¢ ğŸ”Š Ğ˜Ğ¼ĞµĞµÑ‚ÑÑ Ğ¸Ğ½Ñ‚ĞµĞ³Ñ€Ğ°Ñ†Ğ¸Ñ TTS (Text-To-Speech)."
maxplayers = 180
soft_max_players = 80
map_rotation = true

[server]
lobby_name = "ï¸ğŸ›°ï¸ CorvaxGoob â€” ğŸŒ• Ğ›ÑĞ¼ĞµĞ½ ğŸª [MRP+] [TTS]"

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 1440
min_overall_minutes = 1200
deny_vpn = true
enable_without_admins = true
disable_with_admins = false

[rules]
time = 30.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
