# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

blank_issues_enabled: true
contact_links:
  - name: Request a Feature
    url: https://discord.gg/rGvu9hKffJ
    about: Submit feature requests on our Discord server (https://discord.gg/rGvu9hKffJ).
