- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLoneAbductor
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: LoneAbductorAntag
    roleType: SoloAntagonist
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorAgent
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: AbductorAgentAntag
    roleType: TeamAntagonist
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorScientist
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: AbductorScientistAntag
    roleType: TeamAntagonist
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorVictim
  name: Abductee Role
  components:
  - type: MindRole
    antagPrototype: AbductorVictimAntag
  - type: AbductorVictim
