# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

ï»¿# Configuration preset used on Wizard's Den Centipede

[game]
hostname = "[EN] Wizard's Den Centipede [Oceania]"

[hub]
tags = "lang:en,region:oce,rp:low"
