# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

ï»¿# Configuration preset used on Wizard's Den Miros

[game]
hostname = "[EN] Wizard's Den Miros [EU West 2]"

[hub]
tags = "lang:en,region:eu_w,rp:low"
