# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

ï»¿# Configuration preset used on Wizard's Den Spider

[game]
hostname = "[EN] Wizard's Den Spider [EU West 1]"

[hub]
tags = "lang:en,region:eu_w,rp:low"
