# SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 SETh lafuente <cetaciocascarudo@gmail.com>
# SPDX-FileCopyrightText: 2021 SethLafuente <84478872+SethLafuente@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2021 SweptWasTaken <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2021 Tarlan2 <76408146+Tarlan2@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto <gradientvera@outlook.com>
# SPDX-FileCopyrightText: 2022 ElectroJr <leonsfriedrich@gmail.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Peptide90 <78795277+Peptide90@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Rane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Ripmorld <60119809+UKNOWH@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 T-Stalker <43253663+DogZeroX@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 T-Stalker <le0nel_1van@hotmail.com>
# SPDX-FileCopyrightText: 2022 ZeroDayDaemon <60460608+ZeroDayDaemon@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 keronshb <54602815+keronshb@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 metalgearsloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 2023 Boaz1111 <149967078+Boaz1111@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Gagarinten-Noverdo <71782778+noverd@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 HerCoyote23 <131214189+HerCoyote23@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Kevin Zheng <kevinz5000@gmail.com>
# SPDX-FileCopyrightText: 2023 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 2023 Nim <128169402+Nimfar11@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Puro <103608145+PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Scribbles0 <91828755+Scribbles0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Stanislav4ix <124695665+Stanislav4ix@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Vordenburg <114301317+Vordenburg@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Whisper <121047731+QuietlyWhisper@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 chromiumboy <50505512+chromiumboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 lapatison <100279397+lapatison@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 liltenhead <104418166+liltenhead@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Alzore <140123969+Blackern5000@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 BramvanZijp <56019239+BramvanZijp@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Cojoke <83733158+Cojoke-dot@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Flareguy <78941145+Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Ghagliiarghii <68826635+Ghagliiarghii@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 GitHubUser53123 <110841413+GitHubUser53123@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nairod <110078045+Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Plykiya <58439124+Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Plykiya <plykiya@protonmail.com>
# SPDX-FileCopyrightText: 2024 SlamBamActionman <slambamactionman@gmail.com>
# SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 2024 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 icekot8 <93311212+icekot8@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 takemysoult <143123247+takemysoult@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 to4no_fix <156101927+chavonadelal@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Milon <milonpl.git@proton.me>
# SPDX-FileCopyrightText: 2025 SX_7 <sn1.test.preria.2002@gmail.com>
# SPDX-FileCopyrightText: 2025 ƒÅda <ss.adasts@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseShieldRecipe
  categories:
  - Tools
  completetime: 4

- type: latheRecipe
  abstract: true
  id: BaseTargetRecipe
  categories:
  - Tools
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  abstract: true
  id: BaseWeaponRecipe
  categories:
  - Weapons

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeMelee
  completetime: 2

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipePractice
  completetime: 4

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeLong
  completetime: 5

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeSidearm
  completetime: 6

## Recipes

# Clothing
- type: latheRecipe
  id: ClothingBackpackElectropack
  result: ClothingBackpackElectropack
  categories:
  - Clothing
  completetime: 4
  materials:
    Steel: 500
    Plastic: 250
    Cloth: 500

- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  categories:
  - Clothing
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: PortableRecharger
  result: PortableRecharger
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 2000
    Uranium: 2000
    Plastic: 1000
    Plasma: 500
    Glass: 500

- type: latheRecipe
  id: ClothingBackpackHarmpack
  result: ClothingBackpackHarmpack
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 2000
    Plastic: 1000
    Plasma: 500
    Gold: 500

# Shields
- type: latheRecipe
  parent: BaseShieldRecipe
  id: RiotShield
  result: RiotShield
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  parent: BaseShieldRecipe
  id: TelescopicShield
  result: TelescopicShield
  materials:
    Steel: 300
    Glass: 800

# Targets
- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetHuman
  result: TargetHuman

- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetClown
  result: TargetClown

- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetSyndicate
  result: TargetSyndicate

# Tools
- type: latheRecipe
  parent: BaseToolRecipe
  id: Handcuffs
  result: Handcuffs
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseToolRecipe
  id: Zipties
  result: Zipties
  materials:
    Plastic: 200

- type: latheRecipe
  parent: BaseToolRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  parent: BaseToolRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  parent: BaseToolRecipe
  id: Flash
  result: Flash
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

## Weapons

# Melee
- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: Stunbaton
  result: Stunbaton
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: Truncheon
  result: Truncheon
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: CombatKnife
  result: CombatKnife
  materials:
    Steel: 250
    Plastic: 100

# Practice weapons
- type: latheRecipe
  parent: BaseWeaponRecipePractice
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipePractice
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

# Long Guns
- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 500
    Uranium: 300

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 350

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 250

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponTemperatureGun
  result: WeaponTemperatureGun
  materials:
    Steel: 2000
    Glass: 500
    Plastic: 500
    Gold: 500

# Sidearms
- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponDisabler
  result: WeaponDisabler
  materials:
    Steel: 300
    Glass: 200
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponDisablerSMG
  result: WeaponDisablerSMG
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponFlareGunSecurity
  result: WeaponFlareGunSecurity
  materials:
    Plastic: 100
    Steel: 400
