# SPDX-FileCopyrightText: 2022 Pancake <Pangogie@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 ninruB <38016303+asperger-sind@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 lapatison <100279397+lapatison@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Rane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Moony <moonheart08@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 ZeroDayDaemon <60460608+ZeroDayDaemon@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Flareguy <78941145+Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 brainfood1183 <113240905+brainfood1183@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Ubaser <134914314+UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Whisper <121047731+QuietlyWhisper@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 IntegerTempest <30300017+IntegerTempest@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 coolmankid12345 <55817627+coolmankid12345@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Fromoriss <106442259+Fromoriss@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Repo <47093363+Titian3@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Doru991 <75124791+Doru991@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Morb <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Alekshhh <44923899+Alekshhh@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Vordenburg <114301317+Vordenburg@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 JoeHammad1844 <130668733+JoeHammad1844@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Ilya246 <57039557+Ilya246@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 crazybrain23 <44417085+crazybrain23@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Nim <128169402+Nimfar11@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Puro <103608145+PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 KEEYNy <128301315+KEEYNy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 GoodWheatley <109803540+GoodWheatley@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 keronshb <54602815+keronshb@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aviu00 <93730715+Aviu00@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Brandon Hu <103440971+Brandon-Huu@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Verm <32827189+Vermidia@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Golinth <amh2023@gmail.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Plykiya <58439124+Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Firewatch <54725557+musicmanvr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Sphiral <145869023+SphiraI@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Vasilis <vasilis@pikachu.systems>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#Misc outfit startingGear definitions.

#Skeleton Biker - Just a skeleton now
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes

# Syndicate Operative Outfit - Civilian
- type: startingGear
  id: SyndicateOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlack
    id: SyndiPDA
    ears: ClothingHeadsetAltSyndicate

# Syndicate Footsoldier Gear - No Headset
- type: startingGear
  id: SyndicateFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  parent: SyndicateOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    eyes: ClothingEyesHudSyndicate
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombatFilled
  storage:
    back:
    - BoxSurvivalSyndicate

- type: startingGear
  id: SyndicateFootsoldierTeamLeaderGear
  parent: SyndicateFootsoldierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    head: ClothingHeadHatOutlawHat
    outerClothing: ClothingOuterArmorBasicSlim
    back: ClothingBackpackSatchel
    pocket1: BaseUplinkRadio125TC
    pocket2: EnergySword

# Nanotrasen Paramilitary Unit Gear
- type: startingGear
  id: NanotrasenParamilitaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSlotsSecurity # Goobstation - Slots Based Survival Boxes
    - Flash
    - MagazinePistol

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue

- type: startingGear
  id: MobMonkeyGear
  equipment:
    head: ClothingHeadHatTophat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    id: PunPunIDCard

# DeathMatch Gear

- type: startingGear
  id: DeathMatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
  inhand:
    - WeaponMeleeToolboxRobust

#Brigmedic

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretBrigmedic
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltMedicalFilled

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelHolding
    id: AdminPDA
  storage:
    back:
    - GasAnalyzer
    - trayScanner
    - AccessConfiguratorUniversal
    - Multitool

#Gladiator with spear
- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult

#Ash Walker
- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult

#Banana Clown
- type: startingGear
  id: BananaClown
  equipment:
    id: VisitorPDA
    back: ClothingBackpackClown
    shoes: ClothingShoesClownBanana
    jumpsuit: ClothingUniformJumpsuitClownBanana
    mask: ClothingMaskClownBanana
    pocket1: BikeHorn
    pocket2: ClownRecorder

# Passenger but without the ID, bag, or headset
- type: startingGear
  id: LimitedPassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack