# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

- type: chameleonOutfit
  id: SusChameleonOutfit
  loadoutName: chameleon-outfit-sus-name
  name: job-name-passenger
  icon: "JobIconPassenger"
  equipment:
    head: ClothingHeadHatBeret
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetGrey
    mask: ClothingMaskGas
    outerClothing: ClothingOuterVest
    jumpsuit: ClothingUniformJumpsuitColorBlack
    neck: ClothingNeckScarfStripedRed
    back: ClothingBackpack
    gloves: ClothingHandsGlovesColorBlack
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
