#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: WizardPDA
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltWand
    # pocket1: TODO: Include wizard teleport scroll
    pocket2: WizardsGrimoire
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes

- type: startingGear
  id: WizardRedGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed

- type: startingGear
  id: WizardVioletGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet

- type: startingGear
  id: WizardHardsuitGear
  parent: WizardVioletGear
  equipment:
    outerClothing: ClothingOuterHardsuitWizard
