## Static
- type: latheRecipePack
  id: SecurityAmmoStaticGoob
  recipes:
  - MagazineMagnumEmpty
  - MagazineMagnum
  - MagazineBoxShotgunHighCaliber
  - MagazineBoxShotgunSlugHighCaliber
  - MagazineBoxShotgunPracticeHighCaliber

- type: latheRecipePack
  id: SecurityEquipmentStaticGoob
  recipes:
  - GrenadeFlashBang
  - BolaEnergy

- type: latheRecipePack
  id: SecurityHypoStatic
  recipes:
  - CartridgeEpinephrine
  - CartridgeBicaridine
  - CartridgeDermaline
  - SecHypo

## Dynamic
- type: latheRecipePack
  id: SecurityWeaponsGoob
  recipes:
  - WeaponSubMachineSmart

- type: latheRecipePack
  id: SecurityAmmoGoob
  recipes:
  - MagazineSmart
  - MagazineBoxShotgunIncendiaryHighCaliber
  - MagazineBoxShotgunBeanbagHighCaliber
  - MagazineBoxShotgunUraniumHighCaliber

- type: latheRecipePack
  id: SecurityCybernetics
  parent: MedicalCybernetics
  recipes:
  - SecurityCyberneticEyes
