# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

# gloves
- type: entity
  parent: BaseAction
  id: ActionToggleKnuckleDustersStun
  name: Toggle stun knuckle dusters
  description: Toggles the duster's built in stun baton.
  components:
  - type: InstantAction
    event: !type:ToggleActionEvent
