# SPDX-FileCopyrightText: 2024 Ubaser <134914314+UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# For mantles
- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 72000 #20 hrs

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS