- type: job
  id: BlueshieldOfficer
  name: Blueshield Officer
  description: "Act as a bodyguard and advisor for Command and CentCom VIPs."
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 90000 # 25 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 # 25 hours
    - !type:AgeRequirement
      requiredAge: 21
  goobcoins: 45
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - CentralCommand
  - BlueshieldOfficer
  - Service
  - Hydroponics
  - Kitchen
  - Cargo
  - Theatre
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    eyes: ClothingEyesGlassesBSO
    gloves: ClothingHandsGlovesCombat
    id: BlueshieldPDA
    ears: ClothingHeadsetAltCommand
    pocket1: UniqueBlueshieldOfficerLockerTeleporter
    pocket2: PinpointerNuclear
    belt: BlueShieldShieldFilled # I felt like einstein after figuring this out.
  storage:
    back:
    - ClothingMaskGasSecurity 
    - Flash
    - BluespaceLifelineImplanter
    - WeaponEnergyRevolver
    - SecHypo
