- type: entity
  parent: WeaponLaserCarbine
  id: WeaponLaserCarbineRecharging
  categories: [HideSpawnMenu]
  components:
    - type: BatterySelfRecharger
      autoRecharge: true
      autoRechargeRate: 24 # energy shotgun values
      autoRechargePause: true
      autoRechargePauseTime: 30

- type: entity
  parent: WeaponDisabler
  id: WeaponDisablerRecharging
  categories: [HideSpawnMenu]
  components:
    - type: BatterySelfRecharger
      autoRecharge: true
      autoRechargeRate: 20
