- type: job
  id: CommandMaid
  name: job-name-command-maid
  description: job-description-command-maid
  playTimeTracker: JobCommandMaid
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs
    - !type:RoleTimeRequirement
      role: JobJanitor
      time: 3600 #1 hr
  startingGear: CommandMaidGear
  icon: "JobIconCommandMaid"
  supervisors: job-supervisors-command
  setPreference: false
  access:
  - Service
  - Janitor
  - Maintenance
  - Command
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: CommandMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCommandMaid
    id: CommandMaidPDA
    gloves: ClothingHandsGlovesLatex
    ears: ClothingHeadsetCommandService
    eyes: ClothingEyesGlassesCommand
    belt: ClothingBeltJanitorFilled
    shoes: ClothingShoesBootsJackGaloshes
  inhand:
  - AdvMopItem

- type: chameleonOutfit
  id: CommandMaidChameleonOutfit
  job: CommandMaid
  equipment:
    jumpsuit: ClothingUniformJumpskirtCommandMaid
    id: CommandMaidPDA
    gloves: ClothingHandsGlovesLatex
    ears: ClothingHeadsetCommandService
    eyes: ClothingEyesGlassesCommand
    belt: ClothingBeltJanitor
    shoes: ClothingShoesBootsJackGaloshes
