# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 1h
