# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

- type: job
  id: Visitor
  name: job-name-visitor
  description: job-description-visitor
  playTimeTracker: JobVisitor
  canBeAntag: false
  icon: JobIconVisitor
  setPreference: false
  overrideConsoleVisibility: true
  access:
  - Maintenance
  extendedAccess:
  - External
