- type: latheRecipe
  id: GrenadeFlashBang
  result: GrenadeFlashBang
  completetime: 3
  materials:
    Steel: 100
    Plastic: 100

- type: latheRecipe
  id: BolaEnergy
  result: BolaEnergy
  completetime: 3
  materials:
    Steel: 200

- type: latheRecipe
  id: CartridgeEpinephrine
  result: CartridgeEpinephrine
  completetime: 1
  materials:
    Steel: 100
    Glass: 300

- type: latheRecipe
  id: CartridgeAtropine
  result: CartridgeAtropine
  completetime: 1
  materials:
    Steel: 100
    Glass: 300

- type: latheRecipe
  id: CartridgeBicaridine
  result: CartridgeBicaridine
  completetime: 1
  materials:
    Steel: 100
    Glass: 300

- type: latheRecipe
  id: CartridgeDermaline
  result: CartridgeDermaline
  completetime: 1
  materials:
    Steel: 100
    Glass: 300

- type: latheRecipe
  id: CartridgeSaline
  result: CartridgeSaline
  completetime: 1
  materials:
    Steel: 100
    Glass: 300

- type: latheRecipe
  id: CartridgeEphedrine
  result: CartridgeEphedrine
  completetime: 1
  materials:
    Steel: 200
    Glass: 500
    Plasma: 200
    Gold: 200

- type: latheRecipe
  id: CartridgePuncturase
  result: CartridgePuncturase
  completetime: 1
  materials:
    Steel: 200
    Glass: 500
    Plasma: 500
    Gold: 200

- type: latheRecipe
  id: SecHypo
  result: SecHypo
  completetime: 3
  materials:
    Steel: 1500
    Plastic: 800
    Glass: 1200
    Gold: 500

# Guns

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponTemperatureGun
  result: WeaponTemperatureGun
  materials:
    Steel: 1500
    Glass: 800
    Plastic: 500
    Plasma: 500

# Smartgun

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponSubMachineSmart
  result: WeaponSubMachineSmart
  materials:
    Steel: 1800
    Plastic: 750
    Silver: 500
    Gold: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineSmart
  result: MagazineSmart
  materials:
    Steel: 550

# Mech Weapons
- type: latheRecipe
  id: WeaponMechCombatImmolationGun
  result: WeaponMechCombatImmolationGun
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 2800
    Plastic: 1000
    Plasma: 750
    Glass: 500

- type: latheRecipe
  id: WeaponMechCombatSolarisLaser
  result: WeaponMechCombatSolarisLaser
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 1650
    Plastic: 300
    Plasma: 250
    Glass: 200

- type: latheRecipe
  id: WeaponMechCombatFiredartLaser
  result: WeaponMechCombatFiredartLaser
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 1200
    Plastic: 200
    Plasma: 150
    Glass: 50

- type: latheRecipe
  id: WeaponMechCombatUltraRifle
  result: WeaponMechCombatUltraRifle
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 1000
    Plastic: 200

- type: latheRecipe
  id: WeaponMechCombatShotgun
  result: WeaponMechCombatShotgun
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 1600
    Plastic: 550

- type: latheRecipe
  id: WeaponMechCombatShotgunIncendiary
  result: WeaponMechCombatShotgunIncendiary
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 1500
    Plastic: 800
    Plasma: 300

- type: latheRecipe
  id: WeaponMechCombatDisabler
  result: WeaponMechCombatDisabler
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 750
    Glass: 250
    Plastic: 300

- type: latheRecipe
  id: WeaponMechCombatFlashbangLauncher
  result: WeaponMechCombatFlashbangLauncher
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 1200
    Glass: 300
    Plastic: 450

- type: latheRecipe
  id: WeaponMechCombatMissileRack8
  result: WeaponMechCombatMissileRack8
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 2500
    Glass: 1500
    Plastic: 750

- type: latheRecipe
  id: MechEquipmentKineticAccelerator
  result: WeaponMechIndustrialKineticAccelerator
  categories:
  - MechWeapons
  completetime: 10
  materials:
    Steel: 1500
    Glass: 750
    Silver: 150

# Ammo

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolCaselessRifle
  result: MagazinePistolCaselessRifle
  materials:
    Steel: 145

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxCaselessRifle
  result: MagazineBoxCaselessRifle
  materials:
    Steel: 720

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineLightRifleBoxEmpty
  result: MagazineLightRifleBoxEmpty
  materials:
    Steel: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleBox
  result: MagazineLightRifleBox
  materials:
    Steel: 1600

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineHighCaliberEmpty
  result: MagazineHighCaliberEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineHighCaliber
  result: MagazineHighCaliber
  materials:
    Steel: 325

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxHighCaliber
  result: MagazineBoxHighCaliber
  materials:
    Steel: 600

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineMagnumEmpty
  result: MagazineMagnumEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnum
  result: MagazineMagnum
  materials:
    Steel: 165

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunLeverRifleEmpty
  result: MagazineShotgunLeverRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunLeverRifle
  result: MagazineShotgunLeverRifle
  materials:
    Steel: 240

- type: latheRecipe
  parent: BaseGoldCircuitboardRecipe
  icon: { sprite: _Goobstation/Structures/Machines/contraband_detector.rsi, state: icon }
  id: ContrabandDetectorCircuitboard
  result: ContrabandDetectorCircuitboard
  completetime: 4

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunHighCaliber
  result: MagazineBoxShotgunHighCaliber
  materials:
    Steel: 480

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunSlugHighCaliber
  result: MagazineBoxShotgunSlugHighCaliber
  materials:
    Steel: 480
    Plastic: 160

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunIncendiaryHighCaliber
  result: MagazineBoxShotgunIncendiaryHighCaliber
  materials:
    Steel: 160
    Plastic: 320

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunUraniumHighCaliber
  result: MagazineBoxShotgunUraniumHighCaliber
  materials:
    Plastic: 640
    Uranium: 480

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunBeanbagHighCaliber
  result: MagazineBoxShotgunBeanbagHighCaliber
  materials:
    Steel: 320
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunPracticeHighCaliber
  result: MagazineBoxShotgunPracticeHighCaliber
  materials:
    Steel: 160

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolCaselessRifleEmpty
  result: MagazinePistolCaselessRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRifleEmpty
  result: MagazineCaselessRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRifle
  result: MagazineCaselessRifle
  materials:
    Steel: 400

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxAntiMateriel
  result: MagazineBoxAntiMateriel
  materials:
    Steel: 1500
