# SPDX-FileCopyrightText: 2025 GMWQ <garethquaile@gmail.com>
# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 Ilya246 <57039557+Ilya246@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Ilya246 <ilyukarno@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: startingGear
  id: ContractorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    eyes: ClothingEyesHudSyndicate
    mask: ClothingMaskNeckGaiter
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesCombat
    id: SyndiPDANukie
    belt: ClothingBeltSecurityWebbingContractorFilled
    ears: ClothingHeadsetAltSyndicate
    back: ClothingModsuitContractor
    outerClothing: ClothingOuterArmorBasicSlim
    suitstorage: JetpackContractorFilled
    pocket1: WeaponDisablerSyndicate
