# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: BaseMindRoleAntag
  id: DevilMindRole
  name: Devil Role
  components:
  - type: MindRole
    antagPrototype: Devil
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-devil
  - type: DevilRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-changeling
  - type: ChangelingRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeretic
  name: Heretic Role
  components:
  - type: MindRole
    antagPrototype: Heretic
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-heretic
  - type: HereticRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleGhoul
  name: Ghoul
  components:
  - type: MindRole
    antagPrototype: Ghoul
    exclusiveAntag: false
    roleType: Familiar
    subtype: role-subtype-ghoul
  - type: GhoulRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBrainwashed
  name: Brainwashed Role
  components:
  - type: MindRole
    antagPrototype: Mindcontrolled
    exclusiveAntag: true
    roleType: Familiar
    subtype: role-subtype-brainwashed
  - type: MindcontrolledRole

# Slasher
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSlasher
  name: Slasher Role
  components:
  - type: MindRole
    antagPrototype: Slasher
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-slasher

# Goobstation Sentient Animal PR # This role is intended for all animals who aren't explicitly an antag
- type: entity
  parent: [ BaseMindRoleAntag, MindRoleGhostRoleNeutral ]
  id: MindRoleGhostRoleSentientAnimal
  name: Ghost Role (SentientAnimal)
  components:
  - type: MindRole
    roleType: SentientAnimal
    sortWeight: 30
    
#contractor
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleContractor
  name: Contractor Role
  components:
  - type: MindRole
    antagPrototype: Contractor
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-contractor
