# SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2024 starch <starchpersonal@gmail.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2025 Armok <155400926+ARMOKS@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 LuciferMkshelter <154002422+LuciferEOS@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 Ted Lukin <66275205+pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 pheenty <fedorlukin2006@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: playTimeTracker
  id: JobBlueshieldOfficer

- type: playTimeTracker
  id: JobNanotrasenRepresentative

- type: playTimeTracker
  id: JobHecuOperative

- type: playTimeTracker
  id: JobNavyOfficer

- type: playTimeTracker
  id: JobNavyCaptain

- type: playTimeTracker
  id: JobNavyOfficerUndercover

- type: playTimeTracker
  id: JobSpecialOperationsOfficer

- type: playTimeTracker
  id: JobDiplomat

- type: playTimeTracker
  id: JobInspector

- type: playTimeTracker
  id: JobNanotrasenCareerTrainer

- type: playTimeTracker
  id: JobHighCommander

- type: playTimeTracker
  id: JobGovernmentMan

- type: playTimeTracker
  id: JobConquest

- type: playTimeTracker
  id: JobMercenaryCaptain

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobSecurityClown

- type: playTimeTracker
  id: JobCommandMaid

- type: playTimeTracker
  id: JobPartyMaker

- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobVirologist
