# SPDX-FileCopyrightText: 2023 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 keronshb <54602815+keronshb@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: false
  objective: roles-antag-space-ninja-objective
  guides: [ SpaceNinja ]

#Ninja Gear
- type: startingGear
  id: SpaceNinjaGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    back: ClothingBackpackSatchel
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinja
    id: AgentIDCard
    ears: ClothingHeadsetGrey
    pocket1: SpiderCharge
    pocket2: PinpointerStation
    belt: EnergyKatana
  inhand:
    - JetpackBlackFilled
  storage:
    back: # belt holds katana so satchel has the tools for sabotaging things
    - Crowbar
    - Wrench
    - Screwdriver
    - Wirecutter
    - Welder
    - Multitool