# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

- type: antag
  id: SubvertedSilicon
  name: roles-antag-subverted-silicon-name
  antagonist: true
  setPreference: false
  objective: roles-antag-subverted-silicon-objective
