# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 BombasterDS <deniskaporoshok@gmail.com>
# SPDX-FileCopyrightText: 2025 BombasterDS2 <shvalovdenis.workmail@gmail.com>
# SPDX-FileCopyrightText: 2025 Gareth Quaile <garethquaile@gmail.com>
# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 Hanz <41141796+Hanzdegloker@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Nyxilath <colton.malone@gmail.com>
# SPDX-FileCopyrightText: 2025 SX-7 <92227810+SX-7@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 SX-7 <sn1.test.preria.2002@gmail.com>
# SPDX-FileCopyrightText: 2025 SX_7 <sn1.test.preria.2002@gmail.com>
# SPDX-FileCopyrightText: 2025 Ted Lukin <66275205+pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Thinbug <101073555+Thinbug0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 pheenty <fedorlukin2006@gmail.com>
# SPDX-FileCopyrightText: 2025 saga3152 <133799418+saga3152@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
## Static

- type: latheRecipePack
  id: ServiceStatic
  recipes:
  - Bucket
  - Ashtray
  - DrinkMug
  - DrinkMugMetal
  - DrinkGlass
  - DrinkShotGlass
  - DrinkGlassCoupeShaped
  - CustomDrinkJug
  - FoodPlate
  - FoodPlateSmall
  - FoodPlatePlastic
  - FoodPlateSmallPlastic
  - FoodBowlBig
  - FoodPlateTin
  - FoodPlateMuffinTin
  - FoodKebabSkewer
  - LightReplacer
  - SprayBottle
  - TrashBag
  - LightReplacer
  - MopItem
  - Holoprojector
  - WetFloorSign
  - WireBrush

- type: latheRecipePack
  id: ServiceBoardsStatic
  recipes:
  - BiogeneratorMachineCircuitboard
  - UniformPrinterMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ReagentGrinderMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard

## Dynamic

- type: latheRecipePack
  id: Janitor
  recipes:
  - AdvMopItem
  - WeaponSprayNozzle
  - ClothingBackpackWaterTank
  - MegaSprayBottle

- type: latheRecipePack
  id: Instruments
  recipes:
  - SynthesizerInstrument
  - PushHorn

- type: latheRecipePack
  id: ServiceBoards
  recipes:
  - BiofabricatorMachineCircuitboard
  - FatExtractorMachineCircuitboard
  - HydroponicsTrayMachineCircuitboard # roundstart gear being unlocked roundstart when
  - SeedExtractorMachineCircuitboard # ^
  - MassMediaCircuitboard
  - ReagentGrinderIndustrialMachineCircuitboard
  - JukeboxCircuitBoard
  - DawInstrumentMachineCircuitboard
  - SheetifierMachineCircuitboard # Goobstation - Moved from ScienceBoards
