# SPDX-FileCopyrightText: 2024 fishbait <gnesse@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
- type: antag
  id: Blob
  name: roles-antag-blob-name
  antagonist: true
  setPreference: true
  objective: roles-antag-blob-objective
  guides: [ Blob ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h # Goobstation-RoleTime