# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Devil
  name: roles-antag-devil-name
  antagonist: true
  setPreference: true
  objective: roles-antag-devil-description
  guides: [ Devil ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000 # 30h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 18000 # 5 hours
  - !type:RoleTimeRequirement
    role: JobLibrarian # CorvaxGoob; :S_trollface:
    time: 36000 # 10 Hour CorvaxGoob: from 1 hour to 10
  - !type:SpeciesRequirement
    inverted: true
    species:
    - Plasmaman
    - Abductor # CorvaxGoob-Species

- type: startingGear
  id: DevilStartingGear
  storage:
    back:
    - GuidebookCodexUmbra
    - PenDevil
    - ClothingEyesGlassesSunglasses
    - ClothingUniformJumpsuitDevil
