- type: antag
  id: SleeperChangeling
  name: roles-antag-changelingmidround-name
  antagonist: true
  setPreference: true
  objective: roles-antag-changeling-description
  requirements:
  - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
    - Plasmaman
  guides: [ Changelings ]

- type: antag
  id: SleeperHeretic
  name: roles-antag-hereticmidround-name
  antagonist: true
  setPreference: true
  objective: roles-antag-heretic-description
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15h
  guides: [ Heretics ]

- type: antag
  id: SleeperDevil
  name: roles-antag-devilmidround-name
  antagonist: true
  setPreference: true
  objective: roles-antag-devil-description
  guides: [ Devil ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000 # 30h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 18000 # 5 hours
  - !type:RoleTimeRequirement
    role: JobLawyer
    time: 3600 # 1 Hour
  - !type:SpeciesRequirement
    inverted: true
    species:
    - Plasmaman
