- type: startingGear
  id: GreyTideAntagGear
  equipment:
    mask: ClothingMaskGasUnremoveable
    jumpsuit: ClothingUniformJumpsuitAncientUnremoveable
    shoes: ClothingShoesColorBlackUnremoveable
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    belt: ClothingBeltUtilityFilledUnremoveable
    gloves: ClothingHandsGlovesColorYellowUnremovable
    back: ClothingBackpackUnremoveable
  inhand:
  - Toolboxrobust

- type: startingGear
  id: TunnelClownAntagGear
  equipment:
    mask: ClothingMaskClownUnremoveable
    jumpsuit: ClothingUniformJumpsuitClown
    outerClothing: ClothingOuterCoatJacketBiker
    shoes: ClothingShoesClownUnremoveable
    id: ClownPDA
    ears: ClothingHeadsetService
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackClown
  inhand:
  - FireAxe
  - Stunprod
  storage:
    back:
    - ClownRecorder
    - FoodMeatClown
    - TunnelClownBusinessCard

- type: startingGear
  id: SingulothKnightsAntagGear
  equipment:
    head: ClothingHeadSinguloth
    jumpsuit: ClothingUniformJumpsuitColorBlack
    outerClothing: ClothingSingulothArmor
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesColorYellow
    back: ClothingBackpackSatchelLeather
    belt: ClothingBeltUtilityFilled
  inhand:
  - SingularityHammer
  storage:
    back:
    - MedkitCombatFilled

- type: startingGear
  id: DarkLordAntagGear
  equipment:
    head: ClothingHeadHatHoodVoidCloak
    jumpsuit: ClothingUniformJumpsuitMonasticRobeDark
    outerClothing: ClothingOuterWizardBlackReal
    shoes: ClothingShoesColorBlack
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackSatchelLeather
    id: SyndiPDA
  inhand:
  - EnergySwordDoubleRed
  storage:
    back:
    - BoxSurvivalSlotsSyndicate

- type: startingGear
  id: ChosenOneProtagGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    outerClothing: JediRobes
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltAssaultFilled
    id: CentcomPDA
  inhand:
  - EnergySwordBlue
