- type: startingGear
  id: GreyTideAntagGear
  equipment:
    mask: ClothingMaskGasUnremoveable
    jumpsuit: ClothingUniformJumpsuitAncientUnremoveable
    shoes: ClothingShoesColorBlackUnremoveable
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    belt: ClothingBeltUtilityFilledUnremoveable
    gloves: ClothingHandsGlovesColorYellowUnremovable
    back: ClothingBackpackUnremoveable
  inhand:
  - Toolboxrobust

- type: startingGear
  id: TunnelClownAntagGear
  equipment:
    mask: ClothingMaskClownUnremoveable
    jumpsuit: ClothingUniformJumpsuitClown
    outerClothing: ClothingOuterCoatJacketBiker
    shoes: ClothingShoesClownUnremoveable
    id: ClownPDA
    ears: ClothingHeadsetService
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackClown
  inhand:
  - FireAxe
