# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 loltart <lo1tartyt@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later


- type: antag
  id: CorporateAgent
  name: roles-antag-corporate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-corporate-agent-description
  guides: [ CorporateAgents ]
  requirements:
  - !type:SpeciesRequirement # CorvaxGoob-Species
    inverted: true
    species:
    - Abductor
