- type: entity
  parent: BaseObjective
  id: GrayTideKillEveryoneObjective
  components:
  - type: Objective
    icon:
      sprite: Objects/Tools/Toolboxes/toolbox_red.rsi
      state: icon
    difficulty: 1.5
    issuer: objective-issuer-unknown
  - type: SlaughterKillEveryoneCondition
    title: tide-objective-condition-kill-everyone-else-title
    description: tide-objective-kill-everyone-desc

- type: entity
  parent: BaseObjective
  name: Protect maintenance.
  description: This stations maintenance has been your home for as long as you can remember, hiding from the crew in lockers is all that you've known, until now. Thoses station goers have invaded your home for the last time, kill anyone who dares to distrupt your home.
  id: TunnelClownProtectMaintenanceObjective
  components:
  - type: Objective
    icon:
      sprite: Clothing/Mask/clown.rsi
      state: icon
    difficulty: 1
    issuer: objective-issuer-unknown
  - type: RoleplayObjective
