- type: entity
  parent: BaseObjective
  id: GrayTideBaseObjective
  components:
  - type: Objective
    difficulty: 1.5
    issuer: objective-issuer-unknown


- type: entity
  parent: GrayTideBaseObjective
  id: GrayTideKillEveryoneObjective
  components:
  - type: Objective
    icon:
      sprite: Objects/Tools/Toolboxes/toolbox_red.rsi
      state: icon
  - type: SlaughterKillEveryoneCondition
    title: tide-objective-condition-kill-everyone-else-title
    description: tide-objective-kill-everyone-desc
