# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 Roudenn <romabond091@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: CrateFishingGoodies
  parent: CratePlastic
  name: fishing goodies crate
  description: A couple of fishing rods, a bear, and a hat. Everything you need to catch all fish on the station!
  components:
  - type: StorageFill
    contents:
      - id: FishingRod
      - id: FishingRodGoon
      - id: ClothingHeadFishCap
      - id: DrinkBeerBottleFull

- type: entity
  id: CrateSlotMachine
  parent: CrateGenericSteel
  name: slot machine crate
  description: A crate with a slot machine inside, Everything you need to start your own gambling addiction!
  components:
  - type: StorageFill
    contents:
      - id: SlotMachineFlatpack

- type: entity
  id: CrateCoinFlipper
  parent: CrateGenericSteel
  name: coin flipper crate
  description: A crate with a coin flipper inside, 50/50 odds are good!
  components:
  - type: StorageFill
    contents:
    - id: CoinFlipperFlatPack

- type: entity
  id: CrateClawMachine
  parent: CrateGenericSteel
  name: claw machine crate
  description: A crate with a claw machine inside, plushies included with every purchase!
  components:
  - type: StorageFill
    contents:
    - id: ClawMachineFlatPack

- type: entity
  id: CrateCargoForklift
  parent: CrateLivestock
  name: Forklift crate
  description: A perfect utility vehicle for cargo.
  components:
    - type: StorageFill
      contents:
        - id: VehicleForklift
        - id: VehicleKeyForklift

- type: entity
  id: CrateRadioStationAds
  parent: CrateGenericSteel
  name: ads crate
  description: A whole crate which sole purpose is to store 6 exclusive ads, aint capitalism great?
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: RandomVinylDisk
        rolls: 6

- type: entityTable
  id: RandomVinylDisk
  table: !type:GroupSelector
    children:
    - id: CdDiskDanitosBurritos
      weight: 0.6
    - id: CdDiskBillMovie
      weight: 0.6
    - id: CdDiskCapTraining
      weight: 0.6
    - id: CdDiskCargonia
      weight: 0.6
    - id: CdDiskChemistry
      weight: 0.6
    - id: CdDiskCloningPsa
      weight: 0.6
    - id: CdDiskDansTickets
      weight: 0.6
    - id: CdDiskGrones
      weight: 0.6
    - id: CdDiskPopeCrunchCereal
      weight: 0.6
    - id: CdDiskQuikNoodles
      weight: 0.6
    - id: CdDiskRobotics
      weight: 0.6
    - id: CdDiskSecurityPsa
      weight: 0.6
    - id: CdDiskCommanderAnnouncement
      weight: 0.2
    - id: CdDiskCommanderFigurines
      weight: 0.2
    - id: CdDiskCommanderResignation
      weight: 0.2
    - id: CdDiskCommanderSupport
      weight: 0.2
    - id: CdDiskHeisenbeeTrial
      weight: 0.2
    - id: CdDiskXgOnboarding1
      weight: 0.1
    - id: CdDiskXgOnboarding2
      weight: 0.1
    - id: CdDiskXgOnboarding3
      weight: 0.1
    - id: CdDiskXgOnboarding4
      weight: 0.1
    - id: VinylDiskForgotten
      weight: 0.05
